# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_newspaperarticle_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaperarticle',
            name='url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
